image: golang:latest

services:
  - postgres:9.6

variables:
  POSTGRES_DB: poestatustest
  POSTGRES_USER: poe
  POSTGRES_PASSWORD: poepass
  TEST_DATABASE_URL: postgres://poe:poepass@postgres/poestatustest?sslmode=disable

before_script:
  - apt-get update -qq && apt-get install -y -qq nmap unzip openjdk-8-jdk-headless
  # clojure installation
  - curl -O https://download.clojure.org/install/linux-install-1.10.0.403.sh
  - chmod +x linux-install-1.10.0.403.sh
  - ./linux-install-1.10.0.403.sh
  - rm linux-install-1.10.0.403.sh
  - clojure -e '(println "it works!")'
  # protoc installation
  - curl -OL https://github.com/google/protobuf/releases/download/v3.6.1/protoc-3.6.1-linux-x86_64.zip
  - unzip protoc-3.6.1-linux-x86_64.zip -d protoc3
  - rm protoc-3.6.1-linux-x86_64.zip
  - mv protoc3/bin/* /usr/local/bin/
  - mv protoc3/include/* /usr/local/include/
  - rm protoc3 -rf
  - which protoc
  # go deps
  - go get

stages:
  - test

test:
  stage: test
  script:
    - make clean test

build:
  stage: test
  script:
    - make clean build-binaries release
