image: golang:latest

before_script:
  - apt-get update -qq && apt-get install -y -qq software-properties-common ca-certificates wget
  - add-apt-repository -y ppa:maarten-fonville/protobuf
  - apt-get update -qq && apt-get install -y -qq nmap protobuf
  - go get

stages:
  - test
  - build

test:
  stage: test
  script:
    - make generate
    - make test

build:
  stage: build
  script:
    - make build-binaries
