image: golang:latest

services:
  - postgres:9.6

variables:
  POSTGRES_DB: poestatustest
  POSTGRES_USER: poe
  POSTGRES_PASSWORD: poepass

before_script:
  - apt-get update -qq && apt-get install -y -qq nmap unzip
  - curl -OL https://github.com/google/protobuf/releases/download/v3.6.1/protoc-3.6.1-linux-x86_64.zip
  - unzip protoc-3.6.1-linux-x86_64.zip -d protoc3
  - rm protoc-3.6.1-linux-x86_64.zip
  - mv protoc3/bin/* /usr/local/bin/
  - mv protoc3/include/* /usr/local/include/
  - rm protoc3 -rf
  - which protoc
  - go get

stages:
  - test
  - build

test:
  stage: test
  script:
    - make clean test

build:
  stage: build
  script:
    - make clean build-binaries
