version: 2

jobs:
  build:
    docker:
      - image: circleci/golang:latest
      - image: circleci/postgres:latest
        environment:
          POSTGRES_DB: poestatustest
          POSTGRES_USER: poe

    working_directory: /tmp/{{ORG_NAME}}/{{REPO_NAME}}
    steps:
      - checkout
      - setup_remote_docker
      - run: ./.circleci/deps.sh
      - run: go get
      - run:
          command: make clean test
          environment:
            SKIP_PING: yes
            TEST_DATABASE_URL: postgres://poe@localhost:5432/poestatustest?sslmode=disable
      - run: make docker-build docker-push
  release:
    docker:
      - image: google/cloud-sdk

    working_directory: /tmp/{{ORG_NAME}}/{{REPO_NAME}}
    steps:
      - setup_remote_docker
      - run: |
          echo $GCLOUD_SERVICE_KEY | base64 --decode | gcloud auth activate-service-account --key-file=-
          gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
          gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}
          gcloud auth configure-docker
      - checkout
      - run: apt-get -qq update && apt-get -y -qq install make
      - run: make docker-build docker-push

workflows:
  version: 2
  build_and_release:
    jobs:
      - build
      - release
