version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:latest
      - image: circleci/postgres:latest
        environment:
          POSTGRES_DB: poestatustest
          POSTGRES_USER: poe

    working_directory: /tmp/{{ORG_NAME}}/{{REPO_NAME}}
    steps:
      - checkout
      - run: ./.circleci/deps.sh
      - run: go get
      - run:
          command: make clean test
          environment:
              DATABASE_URL: postgres://poe:@postgres/localhost:5432?sslmode=disable
      - run:
          command: make clean build-binaries release
