name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: golang:latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: poestatustest
          POSTGRES_USER: poe
        ports:
        - "5432:5432"
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
    - uses: actions/checkout@v1
    - name: Deps
      run: ./.github/deps.sh
    - name: CI
      run: make clean test
      env:
        SKIP_PING: yes
        TEST_DATABASE_URL: postgres://poe@localhost:5432/poestatustest?sslmode=disable
